"""Add User

Revision ID: 937b4f3445e8
Revises: 588f413c01e7
Create Date: 2024-03-16 20:58:32.004660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '937b4f3445e8'
down_revision: Union[str, None] = '588f413c01e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('msg_to_send_at', sa.TIMESTAMP(), nullable=False))
    op.drop_column('users', 'msg_sent_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('msg_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'msg_to_send_at')
    # ### end Alembic commands ###
